#!/usr/bin/python

import softlayer_messaging
import datetime

client = softlayer_messaging.get_client('5zdc3')
client.authenticate('SL1187241', '876a3a7bb1114096ce6a48ab6b246d23e3c9b6717dd115b37063680f92acdd04')

# all messages are visible in the queue after 10 seconds and expire after 600 seconds
# client.create_queue(name='cricket_queue_001', visibility_interval=10, expiration=600)

queue = client.queue('cricket_queue_001')
f = open('roy_data.txt', 'r')

for line in f:
  attribute     =       line.split(',')[0]
  value         =       line.split(',')[1]
  device        =       'cricket001'
  queue.push(device, fields={attribute : value}, visibility_delay=0)
  print device, attribute, value
print datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
